/**
 * This file was generated by d7-theme-scaffold compass plugin.
 * It gives you a basic scaffold to start with.
 * You can modify it to fit your personal needs.
 */

(function ($) {
  Drupal.behaviors.MYTHEME = {
    attach: function (context, settings) {
		// code goes here
    }
  };

}(jQuery));